### ISSUE TITLE
Add Flagger to projects

### ISSUE THREAD

**Issue by dholbach** [cncf/cncf-branding#4]
Flagger is part of the Flux project and thus should be added to `data/projects.yaml`.

```yaml
- tag: flagger
  name: Flagger
  status: incubating
  site: https://flagger.app/
  description: Progressive delivery Kubernetes operator (Canary, A/B Testing and Blue/Green deployments) 
  colors:
    primary: ababab
    secondary: ededed
```

@stefanprodan Does the above look good to you?

@bia Can you give me the "real" primary and secondary colours of the Flagger logo?

We will also need to add the Flagger logos to `cncf/artwork`, as we did for Flux here: <https://github.com/cncf/artwork/tree/master/projects/flux>.
